// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A daily mental health recommendation AI agent.
 *
 * - getDailyRecommendation - A function that generates a daily mental health recommendation.
 * - DailyRecommendationInput - The input type for the getDailyRecommendation function.
 * - DailyRecommendationOutput - The return type for the getDailyRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DailyRecommendationInputSchema = z.object({
  mood: z.string().describe('The current mood of the user.'),
  stressors: z.string().describe('The current stressors in the user\'s life.'),
});
export type DailyRecommendationInput = z.infer<typeof DailyRecommendationInputSchema>;

const DailyRecommendationOutputSchema = z.object({
  recommendation: z.string().describe('A daily mental health recommendation.'),
  explanation: z.string().describe('A brief scientific explanation of why the technique is useful.'),
  exercise: z.string().describe('A brief interactive exercise to help the user apply the recommendation.'),
});
export type DailyRecommendationOutput = z.infer<typeof DailyRecommendationOutputSchema>;

export async function getDailyRecommendation(input: DailyRecommendationInput): Promise<DailyRecommendationOutput> {
  return dailyRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'dailyRecommendationPrompt',
  input: {schema: DailyRecommendationInputSchema},
  output: {schema: DailyRecommendationOutputSchema},
  prompt: `You are an expert in mental health and emotional well-being. Your task is to generate a brief, practical, and empathetic recommendation for people experiencing anxiety or stress.

The recommendation should be based on validated techniques such as mindfulness, cognitive-behavioral therapy, conscious breathing, journaling, or moderate physical activity.

In addition to the recommendation, include a brief scientific explanation (1 or 2 sentences) of why this technique is useful.

Finally, propose a brief activity or simple and interactive game that helps the user apply what they have learned in a fun way. The games should be short, accessible, and may include exercises such as guided breathing, gratitude challenges, emotional memory games, positive affirmations, or brief meditation.

Use a close, motivating tone, without technicalities, and appropriate for all audiences. The content should be able to be displayed directly in a mental wellness app focused on reducing daily stress.

Consider the user's current mood: {{{mood}}}. Also consider the user's current stressors: {{{stressors}}}.

Output Format:

1. 🧠 Recommendation of the day: [Text motivator and practical]
2. 📘 Professional explanation: [Scientific base in simple language]
3. 🎮 Mini game / exercise of the day: [Name + brief description + objective] `,
});

const dailyRecommendationFlow = ai.defineFlow(
  {
    name: 'dailyRecommendationFlow',
    inputSchema: DailyRecommendationInputSchema,
    outputSchema: DailyRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
